// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxltehbqnhtyidxjnepp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4bHRlaGJxbmh0eWlkeGpuZXBwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwODkyMzcsImV4cCI6MjA3MTY2NTIzN30.-EpLF1wtaa8BhOjIKvMQ2usMRogFB09muLfuzvkq8mU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});